// const CustomData = Java.loadClass("net.minecraft.world.item.component.CustomData")
const ResourceKey = Java.loadClass("net.minecraft.resources.ResourceKey");
const UpgradeOrbTypeRegistry = Java.loadClass("io.redspace.ironsspellbooks.registries.UpgradeOrbTypeRegistry");

const HEALTH = UpgradeOrbTypeRegistry.HEALTH;
const REALITY_INDEX = ResourceKey.create("irons_spellbooks:upgrade_orb_type", "curseofpandora:reality_index");
// const StockTickerBlockEntity = Java.loadClass("com.simibubi.create.content.logistics.stockTicker.StockTickerBlockEntity")
StartupEvents.registry('item', event => {
    event.create('shh:etihw')
        .tooltip(Text.translate('text.shh.etihw.tooltip'))
        .texture('shh:item/etihw')
        .rarity('epic')

    event.create('shh:hulibugulv')
        .tooltip(Text.translate('text.shh.hulibugulv.tooltip'))
        .texture('shh:item/hulibugulv')
        .food(food => {
            food.nutrition(1)
            food.saturation(15)
            food.alwaysEdible()
            food.fastToEat()
            food.effect('minecraft:health_boost', 3600, 4, 1.0)
            food.effect('minecraft:absorption', 3600, 3, 1.0)
            food.effect('minecraft:regeneration', 400, 2, 1.0)
            food.effect('minecraft:instant_health', 1, 4, 1.0)
            food.removeEffect('minecraft:hunger')
            food.usingConvertsTo('minecraft:paper')
        })
        .maxStackSize(16)
        .rarity('epic')

    event.create('shh:chimings_sword', "sword")
        .maxStackSize(1)
        .maxDamage(1024)
        .rarity('epic')
        .tooltip(Text.translate('text.shh.chimings_sword.tooltip'))
        .texture('shh:item/chimings_sword')

    event.create('shh:maid_tool')
        .maxStackSize(1)
        .rarity('epic')

    event.create("shh:reality_index_upgrade_orb")
        .component("irons_spellbooks:upgrade_orb_type", REALITY_INDEX)
        
    if (CreateEvents) {
        event.create('shh:incomplete_upgrade_advanced_infinity', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_advanced_infinity')
        event.create('shh:incomplete_upgrade_anti_gravity', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_anti_gravity')
        event.create('shh:incomplete_upgrade_blackstone', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_blackstone')
        event.create('shh:incomplete_upgrade_cleanse', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_cleanse')
        event.create('shh:incomplete_upgrade_corrosion', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_corrosion')
        event.create('shh:incomplete_upgrade_curse', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_curse')
        event.create('shh:incomplete_upgrade_damage', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_damage')
        event.create('shh:incomplete_upgrade_double_charge', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_double_charge')
        event.create('shh:incomplete_upgrade_explosion', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_explosion')
        event.create('shh:incomplete_upgrade_explosion_breaker', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_explosion_breaker')
        event.create('shh:incomplete_upgrade_flux_up', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_flux_up')
        event.create('shh:incomplete_upgrade_frozen', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_frozen')
        event.create('shh:incomplete_upgrade_glow', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_glow')
        event.create('shh:incomplete_upgrade_glowing', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_glowing')
        event.create('shh:incomplete_upgrade_harm', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_harm')
        event.create('shh:incomplete_upgrade_heal', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_heal')
        event.create('shh:incomplete_upgrade_levitate', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_levitate')
        event.create('shh:incomplete_upgrade_levitation', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_levitation')
        event.create('shh:incomplete_upgrade_magnify_x2', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_magnify_x2')
        event.create('shh:incomplete_upgrade_magnify_x4', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_magnify_x4')
        event.create('shh:incomplete_upgrade_magnify_x8', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_magnify_x8')
        event.create('shh:incomplete_upgrade_poison', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_poison')
        event.create('shh:incomplete_upgrade_punch', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_punch')
        event.create('shh:incomplete_upgrade_railgun', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_railgun')
        event.create('shh:incomplete_upgrade_slowness', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_slowness')
        event.create('shh:incomplete_upgrade_soul_fire', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_soul_fire')
        event.create('shh:incomplete_upgrade_super_damage', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_super_damage')
        event.create('shh:incomplete_upgrade_void', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_void')
        event.create('shh:incomplete_upgrade_weak', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_weak')
        event.create('shh:incomplete_upgrade_wither', "create:sequenced_assembly")
            .texture('shh:item/incomplete_upgrade_wither')
    } else {
        event.create('shh:incomplete_upgrade_advanced_infinity')
            .texture('shh:item/incomplete_upgrade_advanced_infinity')
        event.create('shh:incomplete_upgrade_anti_gravity')
            .texture('shh:item/incomplete_upgrade_anti_gravity')
        event.create('shh:incomplete_upgrade_blackstone')
            .texture('shh:item/incomplete_upgrade_blackstone')
        event.create('shh:incomplete_upgrade_cleanse')
            .texture('shh:item/incomplete_upgrade_cleanse')
        event.create('shh:incomplete_upgrade_corrosion')
            .texture('shh:item/incomplete_upgrade_corrosion')
        event.create('shh:incomplete_upgrade_curse')
            .texture('shh:item/incomplete_upgrade_curse')
        event.create('shh:incomplete_upgrade_damage')
            .texture('shh:item/incomplete_upgrade_damage')
        event.create('shh:incomplete_upgrade_double_charge')
            .texture('shh:item/incomplete_upgrade_double_charge')
        event.create('shh:incomplete_upgrade_explosion')
            .texture('shh:item/incomplete_upgrade_explosion')
        event.create('shh:incomplete_upgrade_explosion_breaker')
            .texture('shh:item/incomplete_upgrade_explosion_breaker')
        event.create('shh:incomplete_upgrade_flux_up')
            .texture('shh:item/incomplete_upgrade_flux_up')
        event.create('shh:incomplete_upgrade_frozen')
            .texture('shh:item/incomplete_upgrade_frozen')
        event.create('shh:incomplete_upgrade_glow')
            .texture('shh:item/incomplete_upgrade_glow')
        event.create('shh:incomplete_upgrade_glowing')
            .texture('shh:item/incomplete_upgrade_glowing')
        event.create('shh:incomplete_upgrade_harm')
            .texture('shh:item/incomplete_upgrade_harm')
        event.create('shh:incomplete_upgrade_heal')
            .texture('shh:item/incomplete_upgrade_heal')
        event.create('shh:incomplete_upgrade_levitate')
            .texture('shh:item/incomplete_upgrade_levitate')
        event.create('shh:incomplete_upgrade_levitation')
            .texture('shh:item/incomplete_upgrade_levitation')
        event.create('shh:incomplete_upgrade_magnify_x2')
            .texture('shh:item/incomplete_upgrade_magnify_x2')
        event.create('shh:incomplete_upgrade_magnify_x4')
            .texture('shh:item/incomplete_upgrade_magnify_x4')
        event.create('shh:incomplete_upgrade_magnify_x8')
            .texture('shh:item/incomplete_upgrade_magnify_x8')
        event.create('shh:incomplete_upgrade_poison')
            .texture('shh:item/incomplete_upgrade_poison')
        event.create('shh:incomplete_upgrade_punch')
            .texture('shh:item/incomplete_upgrade_punch')
        event.create('shh:incomplete_upgrade_railgun')
            .texture('shh:item/incomplete_upgrade_railgun')
        event.create('shh:incomplete_upgrade_slowness')
            .texture('shh:item/incomplete_upgrade_slowness')
        event.create('shh:incomplete_upgrade_soul_fire')
            .texture('shh:item/incomplete_upgrade_soul_fire')
        event.create('shh:incomplete_upgrade_super_damage')
            .texture('shh:item/incomplete_upgrade_super_damage')
        event.create('shh:incomplete_upgrade_void')
            .texture('shh:item/incomplete_upgrade_void')
        event.create('shh:incomplete_upgrade_weak')
            .texture('shh:item/incomplete_upgrade_weak')
        event.create('shh:incomplete_upgrade_wither')
            .texture('shh:item/incomplete_upgrade_wither')
    }

    event.create("shh:unbreakable")
})

StartupEvents.registry('block', event => {
    event.create("shh:packages_transportation_unit")
        .tagBlock(['create:wrench_pickup'])
        .blockEntity(info => {
            info.inventory("shh", ["down", "east", "north", "south", "up", "west"], 1, 1, item => item.hasTag("create:packages"))
            info.tickFrequency(20)
            info.serverTicking()
        })

})

StartupEvents.registry("fluid", event => {
    event.create("shh:hostility")
        .tint(0xcc71ec)
        .noBlock()
        .noBucket()
})

StartupEvents.registry('creative_mode_tab', event => {
    event.create('shh:shh_stuffs')
        .content(() => ['shh:etihw', 'shh:hulibugulv', 'shh:chimings_sword', 'shh:maid_tool'])
        .translationKey('itemGroup.shh.shh_stuffs')
        .icon(() => 'shh:etihw')
})

// StartupEvents.postInit(event => {

// })