[goggles]
enhancedInfo = true
hideStaticKineticInfo = false
betterStoreInfo = true
renderExtraItems = true
enableKineticEffect = true
preciseNumber = true
disableScreenGoggles = true
betterLine = true
[gameMode]
enableInSurvival = true
enableInCreative = true
enableInSpectator = true
enableInAdventure = true
[delayRender]
renderAnalogBox = true
delayRenderDuration = 60
airBoxPushColor = 14532966
airBoxPullColor = 8375776
[chainConveyor]
alwaysAllowRiding = false
preventFalling = false
enhancedConnection = true
cardBoardedYourself = false
[wrench]
alwaysAllowRotating = true
removeCooldown = true
[misc]
removeCardboardOverlay = true
removeNetheriteFirstPerson = false
removeDivingBootsAffect = false
fixSchematicName = true
rightClickPenetrate = false
rainbowDebug = false
forcedBackend = false
nbtFix = false
showScrapContent = true
