[goggles]
enhancedInfo = true
hideStaticKineticInfo = false
betterStoreInfo = true
enableKineticEffect = true
preciseNumber = true
disableScreenGoggles = true
canRenderOnValueBox = false
extraItemTooltip = false
[gameMode]
enableGoggles = true
enableInSurvival = true
enableInCreative = true
enableInSpectator = true
enableInAdventure = true
[overlay]
renderItemOverlay = true
overlayOffsetX = 0
overlayOffsetY = 0
tooltipFlagType = "Default"
tooltipTheme = "Create"
useCustomColor = false
backgroundColor = 0
borderTopColor = 0
borderBottomColor = 0
[outliner]
renderAnalogBox = true
betterLine = true
delayRenderDuration = 60
outColor = 14532966
inColor = 8375776
rainbowDebug = false
[chainConveyor]
alwaysAllowRiding = false
preventFalling = true
enhancedConnection = true
cardBoardedYourself = false
[wrench]
fixRotationMenu = true
betterEncasedCogwheel = false
betterEncasedPipe = false
betterChassis = false
alwaysShowScrollValue = true
alwaysAllowRotating = false
leftClickFastDismantle = false
removeCooldown = true
enchancedRotationMenu = false
[misc]
removeMechanicalArmLimit = false
preventSelectionDiscard = true
infEditBoxLength = true
removeCardboardOverlay = false
removeNetheriteFirstPerson = false
allowDivingBoot = true
fixSchematicName = true
forcedBackend = false
nbtFix = true
showScrapContent = true
