[goggles]
enhancedInfo = true
hideStaticKineticInfo = false
betterStoreInfo = true
renderExtraItems = true
enableKineticEffect = true
preciseNumber = true
disableScreenGoggles = true
canRenderOnValueBox = false
betterLine = true
overlayOffsetX = 0
overlayOffsetY = 0
[gameMode]
enableGoggle = true
enableInSurvival = true
enableInCreative = true
enableInSpectator = true
enableInAdventure = true
[outlineRenderer]
renderAnalogBox = true
delayRenderDuration = 60
windPushColor = 14532966
windPullColor = 8375776
rainbowDebug = false
[chainConveyor]
alwaysAllowRiding = false
preventFalling = false
enhancedConnection = true
cardBoardedYourself = false
[wrench]
fixRotationMenu = true
betterEncasedCogwheel = true
betterEncasedPipe = true
betterChassis = true
alwaysShowScrollValue = true
alwaysAllowRotating = true
leftClickFastDismantle = true
removeCooldown = true
enchancedRotationMenu = false
[misc]
translateCatnip = true
infEditBoxLength = true
removeCardboardOverlay = true
removeNetheriteFirstPerson = false
allowDivingBoot = true
fixSchematicName = true
forcedBackend = false
nbtFix = false
showScrapContent = true
