#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 17 17:39:24 CST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=\u591C\u89C6FullBright2 v2.0.zip
