#Whether to weaken the shield provided by satiated effect.
#If the Satiated Shield Weakness from the Kaleidoscope Compat mod is enabled, its effects will take precedence. And the configuration options of this mod will be disabled.
#是否启用饱腹代偿效果削弱。
#如果《森罗物语：兼容》的饱腹代偿效果削弱被启用，则优先使用它的削弱效果。且本模组的配置项无效。
isWeakenSatiatedShield = true
#If true, the Satiated Shield effect will not apply while the player has the Hunger effect.
#当为 true 时，玩家存在饥饿状态效果时饱腹代偿效果不生效。
satiatedShieldDisableWhenHungryEffect = true
#Minimum Hunger Value required for the Satiated Shield to apply (int).
#If player's Hunger Value is below this, the effect will not apply.
#饱腹代偿生效所需的最小饥饿值（整数）。
#当玩家饥饿值低于该值时，饱腹代偿不生效。
# Default: 14
# Range: 1 ~ 20
satiatedShieldMinFoodLevel = 14
#The exhaustion added each time the player takes damage.
#4 points of exhaustion = 1 point of food/hunger value, and the player can accumulate up to 40 points of exhaustion in 1 game tick.
#For example: if set to 0.5, each point of damage reduced will cause an additional 0.5 exhaustion.
#每次受到伤害时增加的疲劳值。
#4点疲劳值 = 1点饱食度/饥饿值，在 1 游戏刻中玩家最多积累 40 点疲劳值。
#例如：如果设置为 0.5，每点被减免的伤害将额外造成 0.5 点疲劳值。
# Default: 2.0
# Range: 0.0 ~ 40.0
satiatedShieldAdditionalExhaustionPerDamage = 2.0
#The damage reduction percentage of the Satiated Shield effect.
#The <Damage Reduction Amount> is calculated by multiplying the <Original Damage> by the <Damage Reduction Percentage>.
#For example: if set to 0.85, the player will take 15% of the original damage.
#饱腹代偿效果的<伤害减免百分比>。
#玩家受到的<原始伤害>将乘以<伤害减免百分比>来计算<伤害减免量>。
#例如：如果设置为 0.85，玩家将受到 15% 的原始伤害。
# Default: 0.85
# Range: 0.0 ~ 1.0
satiatedShieldDamageReductionPercent = 0.85
#The maximum damage reduction amount of the Satiated Shield effect.
#If the <Damage Reduction Amount> calculated by multiplying the <Original Damage> by the <Damage Reduction Percentage> is greater than this value, it will be limited to this value.
#For example: if set to 10.0, the damage the player takes will be limited to a maximum reduction of 10 points of damage.
#饱腹代偿效果的<最大伤害减免量>。
#<伤害减免量>大于该值时，将被限制为该值。
#例如：如果设置为 10.0，玩家受到的伤害将被限制为最多减少 10 点伤害。
# Default: 10.0
# Range: 0.0 ~ 1.7976931348623157E308
satiatedShieldMaxDamageReduction = 10.0
#The minimum damage that can be got in the Satiated Shield effect.
#If the <Final Damage> after damage reduction is less than this value, it will be limited to this value.
#<Final Damage> = <Original Damage> - <Damage Reduction Amount>
#饱腹代偿效果下可造成的最小伤害。
#<原始伤害>高于该值时，<最终伤害>将被限制为不低于该值。
#<最终伤害> = <原始伤害> - <伤害减免量>
# Default: 2.0
# Range: 0.0 ~ 1.7976931348623157E308
satiatedShieldMinDamageReduction = 2.0
#The multiplier for the exhaustion added per point of Satiated Shield Weakness Damage.
#4 points of exhaustion = 1 point of food/hunger value, and the player can accumulate up to 40 points of exhaustion in 1 game tick.
#当玩家受到饱腹代偿弱点伤害时，每点伤害增加的疲劳值的乘算倍率。
#4点疲劳值 = 1点饱食度/饥饿值，在 1 游戏刻中玩家最多积累 40 点疲劳值。
# Default: 2.0
# Range: 1.0 ~ 1.7976931348623157E308
satiatedShieldWeaknessDamageMultiplier = 2.0
