[milestones]
#Number of hearts you start out with.
# Default: 10
# Range: 0 ~ 1000
baseHearts = 10
#Number of hearts you gain for reaching a new milestone.
# Default: 2
# Range: 0 ~ 1000
heartsPerMilestone = 1.5
#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
milestones = [
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	8,
	9,
	10,
	11,
	12,
	13,
	14,
	15,
	16,
	17,
	18,
	19,
	20,
	21,
	22,
	23,
	24,
	25,
	26,
	27,
	28,
	29,
	30,
	31,
	32,
	33,
	34,
	35,
	36,
	37,
	38,
	39,
	40,
	41,
	42,
	43,
	44,
	45,
	46,
	47,
	48,
	49,
	50,
	51,
	52,
	53,
	54,
	55,
	56,
	57,
	58,
	59,
	60,
	61,
	62,
	63,
	64,
	65,
	66,
	67,
	68,
	69,
	70
]

[filtering]
#Foods in this list won't affect the player's health nor show up in the food book.
blacklist = []
#When this list contains anything, the blacklist is ignored and instead only foods from here count.
whitelist = [
	"kaleidoscope_cookery:chicken_and_mushroom_stew",
	"kaleidoscope_cookery:cold_style_sashimi",
	"kaleidoscope_cookery:pork_bone_soup",
	"kaleidoscope_cookery:braised_beef_with_potatoes",
	"kaleidoscope_cookery:baozi",
	"kaleidoscope_cookery:frost_lamb_chop",
	"kaleidoscope_cookery:udon_noodle",
	"kaleidoscope_cookery:dongpo_pork",
	"kaleidoscope_cookery:nether_style_sashimi",
	"kaleidoscope_cookery:braised_beef",
	"kaleidoscope_cookery:sweet_and_sour_pork_rice_bowl",
	"kaleidoscope_cookery:sweet_and_sour_pork",
	"kaleidoscope_cookery:tomato_beef_brisket_soup",
	"kaleidoscope_cookery:scramble_egg_with_tomatoes_rice_bowl",
	"kaleidoscope_cookery:scramble_egg_with_tomatoes",
	"kaleidoscope_cookery:country_style_mixed_vegetables",
	"kaleidoscope_cookery:sweet_and_sour_ender_pearls",
	"kaleidoscope_cookery:beef_noodle",
	"kaleidoscope_cookery:beef_meatball_soup",
	"kaleidoscope_cookery:stir_fried_beef_offal_rice_bowl",
	"kaleidoscope_cookery:stir_fried_beef_offal",
	"kaleidoscope_cookery:cooked_donkey_meat",
	"kaleidoscope_cookery:cooked_lamb_chops",
	"kaleidoscope_cookery:cooked_cow_offal",
	"kaleidoscope_cookery:cooked_cut_small_meats",
	"kaleidoscope_cookery:cooked_pork_belly",
	"kaleidoscope_cookery:yakitori",
	"kaleidoscope_cookery:samsa",
	"kaleidoscope_cookery:blaze_lamb_chop",
	"kaleidoscope_cookery:seafood_miso_soup",
	"kaleidoscope_cookery:pufferfish_soup",
	"kaleidoscope_cookery:desert_style_sashimi",
	"kaleidoscope_cookery:shengjian_mantou",
	"kaleidoscope_cookery:crystal_lamb_chop",
	"kaleidoscope_cookery:end_style_sashimi",
	"kaleidoscope_cookery:fearsome_thick_soup",
	"kaleidoscope_cookery:tundra_style_sashimi",
	"kaleidoscope_cookery:fondant_spider_eye",
	"kaleidoscope_cookery:fondant_pie",
	"kaleidoscope_cookery:delicious_egg_fried_rice",
	"kaleidoscope_cookery:hui_noodle",
	"kaleidoscope_cookery:borscht",
	"kaleidoscope_cookery:braised_fish_rice_bowl",
	"kaleidoscope_cookery:braised_fish",
	"kaleidoscope_cookery:braised_beef_rice_bowl",
	"kaleidoscope_cookery:slime_ball_meal",
	"kaleidoscope_cookery:golden_salad",
	"kaleidoscope_cookery:spicy_chicken",
	"kaleidoscope_cookery:spicy_chicken_rice_bowl",
	"kaleidoscope_cookery:wild_mushroom_rabbit_soup",
	"kaleidoscope_cookery:stir_fried_pork_with_peppers",
	"kaleidoscope_cookery:stir_fried_pork_with_peppers_rice_bowl",
	"kaleidoscope_cookery:dumpling",
	"kaleidoscope_cookery:meat_pie",
	"kaleidoscope_cookery:pan_seared_knight_steak",
	"kaleidoscope_cookery:donkey_soup",
	"kaleidoscope_cookery:donkey_burger",
	"kaleidoscope_cookery:fish_flavored_shredded_pork",
	"kaleidoscope_cookery:fish_flavored_shredded_pork_rice_bowl",
	"kaleidoscope_cookery:egg_fried_rice",
	"kaleidoscope_cookery:lamb_and_radish_soup",
	"kaleidoscope_cookery:chorus_fried_egg",
]
#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
# Default: 1
# Range: 0 ~ 1000
minimumFoodValue = 0

[miscellaneous]
#Whether or not to reset the food list on death, effectively losing all bonus hearts.
resetOnDeath = false
#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
limitProgressionToSurvival = false
